from django.db import models

class AnnualReport(models.Model):
    COUNTIES = (
       ("ANDERSON", "Anderson"),
       ("ANDREWS", "Andrews"),
       ("ANGELINA", "Angelina"),
       ("ARANSAS", "Aransas"),
       ("ARCHER", "Archer"),
       ("ARMSTRONG", "Armstrong"),
       ("ATASCOSA", "Atascosa"),
       ("AUSTIN", "Austin"),
       ("BAILEY", "Bailey"),
       ("BANDERA", "Bandera"),
       ("BASTROP   ", "Bastrop"),
       ("BAYLOR", "Baylor"),
       ("BEE", "Bee"),
       ("BELL", "Bell"),
       ("BEXAR", "Bexar"),
       ("BLANCO", "Blanco"),
       ("BORDEN", "Borden"),
       ("BOSQUE", "Bosque"),
       ("BOWIE", "Bowie"),
       ("BRAZORIA", "Brazoria"),
       ("BRAZOS", "Brazos"),
       ("BREWSTER", "Brewster"),
       ("BRISCOE", "Briscoe"),
       ("BROOKS", "Brooks"),
       ("BROWN", "Brown"),
       ("BURLESON", "Burleson"),
       ("BURNET", "Burnet"),
       ("CALDWELL", "Caldwell"),
       ("CALHOUN", "Calhoun"),
       ("CALLAHAN", "Callahan"),
       ("CAMERON", "Cameron"),
       ("CAMP", "Camp"),
       ("CARSON", "Carson"),
       ("CASS", "Cass"),
       ("CASTRO", "Castro"),
       ("CHAMBERS", "Chambers"),
       ("CHEROKEE", "Cherokee"),
       ("CHILDRESS", "Childress"),
       ("CLAY", "Clay"),
       ("COCHRAN", "Cochran"),
       ("COKE", "Coke"),
       ("COLEMAN", "Coleman"),
       ("COLLIN", "Collin"),
       ("COLLINGSWORTH", "Collingsworth"),
       ("COLORADO", "Colorado"),
       ("COMAL", "Comal"),
       ("COMANCHE", "Comanche"),
       ("CONCHO", "Concho"),
       ("COOKE", "Cooke"),
       ("CORYELL", "Coryell"),
       ("COTTLE", "Cottle"),
       ("CRANE", "Crane"),
       ("CROCKETT", "Crockett"),
       ("CROSBY", "Crosby"),
       ("CULBERSON", "Culberson"),
       ("DALLAM", "Dallam"),
       ("DALLAS", "Dallas"),
       ("DAWSON", "Dawson"),
       ("DE WITT", "De Witt"),
       ("DEAF SMITH", "Deaf Smith"),
       ("DELTA", "Delta"),
       ("DENTON", "Denton"),
       ("DICKENS", "Dickens"),
       ("DIMMIT", "Dimmit"),
       ("DONLEY", "Donley"),
       ("DUVAL", "Duval"),
       ("EASTLAND", "Eastland"),
       ("ECTOR", "Ector"),
       ("EDWARDS", "Edwards"),
       ("EL PASO", "El Paso"),
       ("ELLIS", "Ellis"),
       ("ERATH", "Erath"),
       ("FALLS", "Falls"),
       ("FANNIN", "Fannin"),
       ("FAYETTE", "Fayette"),
       ("FISHER", "Fisher"),
       ("FLOYD", "Floyd"),
       ("FOARD", "Foard"),
       ("FORT BEND", "Fort Bend"),
       ("FRANKLIN", "Franklin"),
       ("FREESTONE", "Freestone"),
       ("FRIO", "Frio"),
       ("GAINES", "Gaines"),
       ("GALVESTON", "Galveston"),
       ("GARZA", "Garza"),
       ("GILLESPIE", "Gillespie"),
       ("GLASSCOCK", "Glasscock"),
       ("GOLIAD", "Goliad"),
       ("GONZALES", "Gonzales"),
       ("GRAY", "Gray"),
       ("GRAYSON", "Grayson"),
       ("GREGG", "Gregg"),
       ("GRIMES", "Grimes"),
       ("GUADALUPE", "Guadalupe"),
       ("HALE", "Hale"),
       ("HALL", "Hall"),
       ("HAMILTON", "Hamilton"),
       ("HANSFORD", "Hansford"),
       ("HARDEMAN", "Hardeman"),
       ("HARDIN", "Hardin"),
       ("HARRIS", "Harris"),
       ("HARRISON", "Harrison"),
       ("HARTLEY", "Hartley"),
       ("HASKELL", "Haskell"),
       ("HAYS", "Hays"),
       ("HEMPHILL", "Hemphill"),
       ("HENDERSON", "Henderson"),
       ("HIDALGO", "Hidalgo"),
       ("HILL", "Hill"),
       ("HOCKLEY", "Hockley"),
       ("HOOD", "Hood"),
       ("HOPKINS", "Hopkins"),
       ("HOUSTON", "Houston"),
       ("HOWARD", "Howard"),
       ("HUDSPETH", "Hudspeth"),
       ("HUNT", "Hunt"),
       ("HUTCHINSON", "Hutchinson"),
       ("IRION", "Irion"),
       ("JACK", "Jack"),
       ("JACKSON", "Jackson"),
       ("JASPER", "Jasper"),
       ("JEFF DAVIS", "Jeff Davis"),
       ("JEFFERSON", "Jefferson"),
       ("JIM HOGG", "Jim Hogg"),
       ("JIM WELLS", "Jim Wells"),
       ("JOHNSON", "Johnson"),
       ("JONES", "Jones"),
       ("KARNES", "Karnes"),
       ("KAUFMAN", "Kaufman"),
       ("KENDALL", "Kendall"),
       ("KENEDY", "Kenedy"),
       ("KENT", "Kent"),
       ("KERR   ", "Kerr   "),
       ("KIMBLE", "Kimble"),
       ("KING", "King"),
       ("KINNEY", "Kinney"),
       ("KLEBERG", "Kleberg"),
       ("KNOX", "Knox"),
       ("LA SALLE", "La Salle"),
       ("LAMAR", "Lamar"),
       ("LAMB", "Lamb"),
       ("LAMPASAS", "Lampasas"),
       ("LAVACA", "Lavaca"),
       ("LEE", "Lee"),
       ("LEON", "Leon"),
       ("LIBERTY", "Liberty"),
       ("LIMESTONE", "Limestone"),
       ("LIPSCOMB", "Lipscomb"),
       ("LIVE OAK", "Live Oak"),
       ("LLANO", "Llano"),
       ("LOVING", "Loving"),
       ("LUBBOCK", "Lubbock"),
       ("LYNN", "Lynn"),
       ("MADISON", "Madison"),
       ("MARION", "Marion"),
       ("MARTIN", "Martin"),
       ("MASON", "Mason"),
       ("MATAGORDA", "Matagorda"),
       ("MAVERICK", "Maverick"),
       ("MCCULLOCH", "McCulloch"),
       ("MCLENNAN", "McLennan"),
       ("MCMULLEN", "McMullen"),
       ("MEDINA", "Medina"),
       ("MENARD", "Menard"),
       ("MIDLAND", "Midland"),
       ("MILAM", "Milam"),
       ("MILLS", "Mills"),
       ("MITCHELL", "Mitchell"),
       ("MONTAGUE", "Montague"),
       ("MONTGOMERY", "Montgomery"),
       ("MOORE", "Moore"),
       ("MORRIS", "Morris"),
       ("MOTLEY", "Motley"),
       ("NACOGDOCHES", "Nacogdoches"),
       ("NAVARRO", "Navarro"),
       ("NEWTON", "Newton"),
       ("NOLAN", "Nolan"),
       ("NUECES", "Nueces"),
       ("OCHILTREE", "Ochiltree"),
       ("OLDHAM", "Oldham"),
       ("ORANGE", "Orange"),
       ("PALO PINTO", "Palo Pinto"),
       ("PANOLA", "Panola"),
       ("PARKER ", "Parker "),
       ("PARMER", "Parmer"),
       ("PECOS", "Pecos"),
       ("POLK", "Polk"),
       ("POTTER", "Potter"),
       ("PRESIDIO", "Presidio"),
       ("RAINS", "Rains"),
       ("RANDALL", "Randall"),
       ("REAGAN", "Reagan"),
       ("REAL", "Real"),
       ("RED RIVER", "Red River"),
       ("REEVES", "Reeves"),
       ("REFUGIO", "Refugio"),
       ("ROBERTS", "Roberts"),
       ("ROBERTSON", "Robertson"),
       ("ROCKWALL", "Rockwall"),
       ("RUNNELS", "Runnels"),
       ("RUSK", "Rusk"),
       ("SABINE", "Sabine"),
       ("SAN AUGUSTINE", "San Augustine"),
       ("SAN JACINTO", "San Jacinto"),
       ("SAN PATRICIO", "San Patricio"),
       ("SAN SABA", "San Saba"),
       ("SCHLEICHER", "Schleicher"),
       ("SCURRY", "Scurry"),
       ("SHACKELFORD", "Shackelford"),
       ("SHELBY", "Shelby"),
       ("SHERMAN", "Sherman"),
       ("SMITH", "Smith"),
       ("SOMERVELL", "Somervell"),
       ("STARR", "Starr"),
       ("STEPHENS", "Stephens"),
       ("STERLING", "Sterling"),
       ("STONEWALL", "Stonewall"),
       ("SUTTON", "Sutton"),
       ("SWISHER", "Swisher"),
       ("TARRANT", "Tarrant"),
       ("TAYLOR", "Taylor"),
       ("TERRELL", "Terrell"),
       ("TERRY", "Terry"),
       ("THROCKMORTON", "Throckmorton"),
       ("TITUS", "Titus"),
       ("TOM GREEN", "Tom Green"),
       ("TRAVIS", "Travis"),
       ("TRINITY", "Trinity"),
       ("TYLER", "Tyler"),
       ("UPSHUR", "Upshur"),
       ("UPTON", "Upton"),
       ("UVALDE", "Uvalde"),
       ("VAL VERDE", "Val Verde"),
       ("VAN ZANDT", "Van Zandt"),
       ("VICTORIA", "Victoria"),
       ("WALKER", "Walker"),
       ("WALLER", "Waller"),
       ("WARD", "Ward"),
       ("WASHINGTON", "Washington"),
       ("WEBB", "Webb"),
       ("WHARTON ", "Wharton "),
       ("WHEELER", "Wheeler"),
       ("WICHITA", "Wichita"),
       ("WILBARGER", "Wilbarger"),
       ("WILLACY", "Willacy"),
       ("WILLIAMSON", "Williamson"),
       ("WILSON", "Wilson"),
       ("WINKLER", "Winkler"),
       ("WISE", "Wise"),
       ("WOOD", "Wood"),
       ("YOAKUM", "Yoakum"),
       ("YOUNG", "Young"),
       ("ZAPATA", "Zapata"),
       ("ZAVAL", "Zaval"),
    )
    RESIDENCES = (
       ("Guardian's home", "Guardian's home"),
       ("Foster or boarding home", "Foster or boarding home"),
       ("Hospital or medical facility", "Hospital or medical facility"),
       ("Nursing home", "Nursing home "),
       ("Relative's home", "Relative's home"),
       ("Other", "Other"),
    )
    ward_county = models.CharField(max_length=20, choices=COUNTIES, default="Harris")
    docket_number = models.CharField(max_length=30, help_text='This is the case number that the court uses to identify the case.', blank=False)
    ward_name = models.CharField(max_length=50, help_text='The full name (including middle name) of the person under guardianship.', blank=False)
    ward_dob = models.DateField(auto_now=False, auto_now_add=False, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')
    ward_current_age = models.IntegerField(help_text='The current age (in years) of the person under guardianship.')
    wards_residence = models.CharField(max_length=20, choices=RESIDENCES, default="Guardian's home")
